# Generated by Django 5.0.7 on 2024-08-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='crested',
            new_name='creаted',
        ),
    ]
